# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Proxy
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.aliyun.com|*.tencentyun.com|mirrors.cloud.tencent.com
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.aliyun.com|*.tencentyun.com|mirrors.cloud.tencent.com
# Mod properties
mod_version=1.5.1
maven_group=com.lirxowo
archives_name=carryonextend-architectury
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
architectury_api_version=20.0.12
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
neoforge_version=26.1.2.94
