architectury {
    common rootProject.enabled_platforms.split(',')
}

sourceSets {
    main {
        resources {
            srcDir(file("src/main/generated"))
            exclude("**/.cache")
        }
    }
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    implementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    // CarryOn mod dependency (compile-only for common module)
    compileOnly "curse.maven:carry-on-274259:8554252"
}
